# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vmware/adc_lab/lab9_3_1/lab9_3_1.srcs/sources_1/ip/ip_counter_24/ip_counter_24.xci
# IP: The module: 'ip_counter_24' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vmware/adc_lab/lab9_3_1/lab9_3_1.srcs/sources_1/ip/ip_counter_24/ip_counter_24_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_counter_24'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/vmware/adc_lab/lab9_3_1/lab9_3_1.srcs/sources_1/ip/ip_counter_24/ip_counter_24.xci
# IP: The module: 'ip_counter_24' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vmware/adc_lab/lab9_3_1/lab9_3_1.srcs/sources_1/ip/ip_counter_24/ip_counter_24_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_counter_24'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
