# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vmware/adc_lab/lab9_3_1/lab9_3_1.srcs/sources_1/ip/clk_5MHz/clk_5MHz.xci
# IP: The module: 'clk_5MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vmware/adc_lab/lab9_3_1/lab9_3_1.srcs/sources_1/ip/clk_5MHz/clk_5MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/vmware/adc_lab/lab9_3_1/lab9_3_1.srcs/sources_1/ip/clk_5MHz/clk_5MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/vmware/adc_lab/lab9_3_1/lab9_3_1.srcs/sources_1/ip/clk_5MHz/clk_5MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/vmware/adc_lab/lab9_3_1/lab9_3_1.srcs/sources_1/ip/clk_5MHz/clk_5MHz.xci
# IP: The module: 'clk_5MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vmware/adc_lab/lab9_3_1/lab9_3_1.srcs/sources_1/ip/clk_5MHz/clk_5MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/vmware/adc_lab/lab9_3_1/lab9_3_1.srcs/sources_1/ip/clk_5MHz/clk_5MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/vmware/adc_lab/lab9_3_1/lab9_3_1.srcs/sources_1/ip/clk_5MHz/clk_5MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
